In [117]:
from __future__ import print_function
import collections
import pickle
import re
import random
import sys
import os 
import time

import gensim
from gensim.models.keyedvectors import KeyedVectors
from gensim.models.fasttext import FastText
from gensim.models import word2vec

from sklearn.model_selection import train_test_split,cross_val_score, cross_val_predict, KFold, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix,precision_recall_fscore_support

import pandas as pd
import numpy as np
from numpy import array
from numpy import asarray
from numpy import zeros
from numpy import cumsum

import tensorflow as tf
import keras
from keras import backend as K
from keras import initializers
from keras.models import Sequential,Model,load_model
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dropout, Activation, Flatten, \
    Embedding, Convolution1D, MaxPooling1D, AveragePooling1D, \
    Input, Dense, merge, Add,TimeDistributed, Bidirectional,SpatialDropout1D, \
    Concatenate, concatenate, multiply, Lambda, dot, Layer
from keras.layers.recurrent import LSTM, GRU, SimpleRNN
from keras.regularizers import l2, l1_l2
from keras.constraints import maxnorm
from keras import callbacks
from keras.utils import generic_utils,plot_model
from keras.optimizers import Adadelta,Adam
from keras.callbacks import ModelCheckpoint,EarlyStopping
from keras.wrappers.scikit_learn import KerasClassifier
# from keras.engine.topology import Layer


import matplotlib.image  as mpimg
import matplotlib.pyplot as plt

import sys
import re
import os
from pathlib import Path
from collections import namedtuple
import numpy as np
import pandas as pd
import pickle
import gensim.downloader as gensimapi
from collections import Counter, defaultdict
import ast

In [118]:
!ls

'Cross Lingual Aspect Based Sentiment Analysis- Part 1.ipynb'
'Cross Lingual Aspect Based Sentiment Analysis- Part 2.ipynb'
 Keras.ipynb
'Multilingual  semeval  dataset creation.ipynb'
 results
'Tatoeba Similarity Search.ipynb'
 utils


In [119]:
# data_folder = "../../../corpus/new/preprocess_from_isuru/"
# lankadeepa_data_path = data_folder + 'lankadeepa_tagged_comments.csv'
# gossip_lanka_data_path = data_folder + 'gossip_lanka_tagged_comments.csv'

# lankadeepa_data = pd.read_csv(lankadeepa_data_path)[:9059]
# gossipLanka_data = pd.read_csv(gossip_lanka_data_path)
# gossipLanka_data = gossipLanka_data.drop(columns=['Unnamed: 3'])

# sinhala_data = pd.concat([lankadeepa_data,gossipLanka_data], ignore_index=True)
# sinhala_data.to_csv("../data/sinhala_comments.csv")

In [120]:
# train_aspects_ungrp = pd.read_csv('../data/Train_english_restaurants_ungrp.csv')

In [121]:
train_aspects_ungrp = pd.read_csv('../data/Train_english_restaurants_ungrp.csv')
val_aspects_ungrp2 = pd.read_csv('../data/Valid_english_restaurants_ungrp.csv')
du_aspects_ungrp2  = pd.read_csv('../data/Dutch_restaurants_ungrp.csv')
sp_aspects_ungrp2  = pd.read_csv('../data/Spanish_english_restaurants_ungrp.csv')

sinhala_comments  = pd.read_csv('../data/sinhala_comments.csv')

In [122]:
sinhala_comments = sinhala_comments.loc[sinhala_comments['label'].isin([2, 3, 4])]

In [123]:
(unique, counts) = np.unique(sinhala_comments["label"].values, return_counts = True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[   2 7665]
 [   3 2403]
 [   4 3080]]


In [124]:
train_aspects_ungrp[['text']].to_csv('../data/processed/en_resturant.csv' , header = None , index = None , mode = 'w')
val_aspects_ungrp2[['text']].to_csv('../data/processed/en_val.csv' , header = None , index = None , mode = 'w')
du_aspects_ungrp2[['text']].to_csv('../data/processed/nl_resturant.csv' , header = None , index = None , mode = 'w')
sp_aspects_ungrp2[['text']].to_csv('../data/processed/es_resturant.csv' , header = None , index = None , mode = 'w')

sinhala_comments[['comment']].to_csv('../data/processed/sinhala_comments.csv' , header = None , index = None , mode = 'w')


In [125]:
LASER_PATH = "/home/lahiru/Projects/FYP/LASER/LASER"
sys.path.insert(0, LASER_PATH + '/source/lib')
sys.path.insert(1, LASER_PATH + '/source')

DATA_PATH = Path("../data/processed/")
CACHE_PATH = Path("../cache2/")
CACHE_PATH.mkdir(exist_ok=True)
MODEL_PATH = Path(LASER_PATH + "/models")

os.environ["LASER"] = LASER_PATH 
SPACE_NORMALIZER = re.compile("\s+")
Batch = namedtuple('Batch', 'srcs tokens lengths')

In [126]:
from indexing import IndexLoad, IndexTextOpen, IndexTextQuery, IndexSearchKNN, IndexCreate, IndexSearchMultiple
from embed import SentenceEncoder, EncodeLoad, EncodeFile
from text_processing import Token, BPEfastApply

In [127]:
encoder = SentenceEncoder(
    str(MODEL_PATH / "bilstm.93langs.2018-12-26.pt"),
    max_sentences=None,
    max_tokens=10000,
    cpu=False)
#original : cpu = False

bpe_codes = str(MODEL_PATH / "93langs.fcodes")

for lang in ("en" ,"nl", 'es'): 
    Token(
        str(DATA_PATH / f"{lang}_resturant.csv"), ##english_resturant.txt
        str(CACHE_PATH / f"{lang}_resturant.csv"),
        lang=lang,
        romanize=False,
        lower_case=True, gzip=False,
        verbose=True)
    BPEfastApply(
        str(CACHE_PATH / f"{lang}_resturant.csv"),
        str(CACHE_PATH / f"{lang}_resturant.bpe"),
        bpe_codes,
        verbose=True, over_write=True)
    EncodeFile(
        encoder,
        str(CACHE_PATH / f"{lang}_resturant.bpe"),
        str(CACHE_PATH / f"{lang}_resturant.enc"),
        verbose=True, over_write=True)    
    
    
Token(
    str(DATA_PATH / f"en_val.csv"), ##english_resturant.txt
    str(CACHE_PATH / f"en_val.csv"),
    lang=lang,
    romanize=False,
    lower_case=True, gzip=False,
    verbose=True)
BPEfastApply(
    str(CACHE_PATH / f"en_val.csv"),
    str(CACHE_PATH / f"en_val.bpe"),
    bpe_codes,
    verbose=True, over_write=True)
EncodeFile(
    encoder,
    str(CACHE_PATH / f"en_val.bpe"),
    str(CACHE_PATH / f"en_val.enc"),
    verbose=True, over_write=True)    

 - Tokenizer: en_resturant.csv exists already
 - Tokenizer: nl_resturant.csv exists already
 - Tokenizer: es_resturant.csv exists already
 - Tokenizer: en_val.csv exists already


In [128]:
Token(
    str(DATA_PATH / f"sinhala_comments.csv"), ##english_resturant.txt
    str(CACHE_PATH / f"sinhala_comments.csv"),
    lang="sin",
    romanize=False,
    lower_case=True, gzip=False,
    verbose=True)
BPEfastApply(
    str(CACHE_PATH / f"sinhala_comments.csv"),
    str(CACHE_PATH / f"sinhala_comments.bpe"),
    bpe_codes,
    verbose=True, over_write=True)
EncodeFile(
    encoder,
    str(CACHE_PATH / f"sinhala_comments.bpe"),
    str(CACHE_PATH / f"sinhala_comments.enc"),
    verbose=True, over_write=True)  

 - Tokenizer: sinhala_comments.csv in language sin  
 - fast BPE: processing sinhala_comments.csv
 - Encoder: sinhala_comments.bpe to sinhala_comments.enc
 - Encoder: 13148 sentences in 370s


In [129]:
LASER_PATH = "/home/lahiru/Projects/FYP/LASER/LASER"
sys.path.insert(0, LASER_PATH + '/source/lib')
sys.path.insert(1, LASER_PATH + '/source')

DATA_PATH = Path("../data/processed/")
CACHE_PATH = Path("../cache2/")
CACHE_PATH.mkdir(exist_ok=True)
MODEL_PATH = Path(LASER_PATH + "/models")

os.environ["LASER"] = LASER_PATH 
SPACE_NORMALIZER = re.compile("\s+")
Batch = namedtuple('Batch', 'srcs tokens lengths')

In [130]:
train_en, index_tr_en = IndexCreate(
    str(CACHE_PATH / "en_resturant.enc"), 'FlatL2', verbose=True, save_index=False)
val_en, index_val_en = IndexCreate(
    str(CACHE_PATH / "en_val.enc"), 'FlatL2', verbose=True, save_index=False)

data_du, index_du = IndexCreate(
    str(CACHE_PATH / "nl_resturant.enc"), 'FlatL2', verbose=True, save_index=False)
data_spanish, index_spanish = IndexCreate(
    str(CACHE_PATH / "es_resturant.enc"), 'FlatL2', verbose=True, save_index=False)

data_sinhala, index_sinhala = IndexCreate(
    str(CACHE_PATH / "sinhala_comments.enc"), 'FlatL2', verbose=True, save_index=False)

 - embedding: ../cache2/en_resturant.enc 1656 examples of dim 1024
 - creating FAISS index
 - embedding: ../cache2/en_val.enc 283 examples of dim 1024
 - creating FAISS index
 - embedding: ../cache2/nl_resturant.enc 960 examples of dim 1024
 - creating FAISS index
 - embedding: ../cache2/es_resturant.enc 1416 examples of dim 1024
 - creating FAISS index
 - embedding: ../cache2/sinhala_comments.enc 13148 examples of dim 1024
 - creating FAISS index


In [131]:
def change_target(x):
    if x=='positive':
        return 2
    elif x =='negative':
        return 1
    else:
        return 0 
    
def change_target_sinala(x):
    if x== 4:
        return 2
    elif x == 2:
        return 1
    else:
        return 0 

train_aspects_ungrp['polarities'] = train_aspects_ungrp['polarities'].apply(lambda x: change_target(x))
val_aspects_ungrp2['polarities'] = val_aspects_ungrp2['polarities'].apply(lambda x: change_target(x))
sp_aspects_ungrp2['polarities'] = sp_aspects_ungrp2['polarities'].apply(lambda x: change_target(x))
du_aspects_ungrp2['polarities'] = du_aspects_ungrp2['polarities'].apply(lambda x: change_target(x))

sinhala_comments['label'] = sinhala_comments['label'].apply(lambda x: change_target_sinala(x))

In [132]:
from sklearn.preprocessing import MultiLabelBinarizer
tr_eng =  train_aspects_ungrp['polarities'].values
val_eng =val_aspects_ungrp2['polarities'].values  
y_du  = du_aspects_ungrp2['polarities'].values
y_spainish  = sp_aspects_ungrp2['polarities'].values

y_sinhala  = sinhala_comments['label'].values
tr_eng.shape , val_eng.shape , y_du.shape , y_spainish.shape, y_sinhala.shape

((1656,), (283,), (960,), (1416,), (13148,))

In [133]:
(unique, counts) = np.unique(y_sinhala, return_counts = True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[   0 2403]
 [   1 7665]
 [   2 3080]]


In [134]:
tr_eng = pd.get_dummies(tr_eng).values
val_eng = pd.get_dummies(val_eng).values
y_du = pd.get_dummies(y_du).values
y_spainish = pd.get_dummies(y_spainish).values
y_sinhala = pd.get_dummies(y_sinhala).values

In [135]:
tr_eng[0]

array([0, 0, 1], dtype=uint8)

In [136]:
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler().fit(train_en)
train_std = std_scale.transform(train_en) 
val_std = std_scale.transform(val_en)
dutch_std = std_scale.transform(data_du)
spanish_std = std_scale.transform(data_spanish)
sinhala_std = std_scale.transform(data_sinhala)

In [137]:
X_train, X_test, y_train, y_test = train_test_split(sinhala_std, y_sinhala, test_size=0.2, random_state=0)

In [138]:
type(train_std)

numpy.ndarray

In [146]:
def RNN_model():
    main_input = Input(shape=(1,1024 ), dtype='float', name='main_input')
#     embedding  = Embedding(MAX_FEATURES, EMBEDDING_SIZE
#               , input_length=MAX_LEN,
#               name='embedding' ,trainable=False)(main_input)

    embedding = Dropout(DROPOUT_VALUE_1)(main_input)

    x = RNN(HIDDEN_DIMS)(embedding)

    x = Dense(HIDDEN_DIMS, activation='relu', init='he_normal', 
              W_constraint = maxnorm(3), b_constraint=maxnorm(3),
              name='mlp')(x)

    x = Dropout(DROPOUT_VALUE_2, name='drop')(x)

    output = Dense(3, init='he_normal',
                   activation='softmax', name='output')(x)

    model = Model(input=main_input, output=output ,name="RNN_model")

    model.compile(loss={'output':'categorical_crossentropy'},
              optimizer=Adadelta(lr=0.95, epsilon=1e-06),
              metrics=["accuracy",
                       tf.keras.metrics.Precision(),
                        tf.keras.metrics.Recall(),
                       f1])
    
    print(model.summary())
    return model

def simple_model():
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(512))
    model.add(tf.keras.layers.Dense(256))
    model.add(tf.keras.layers.Dense(3))
    model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=["accuracy"])
    # This builds the model for the first time:
    
    return model

def simple_model2():
    
    model = Sequential()
    model.add(LSTM(32, input_shape=(1024, 1024)))
    model.add(Dense(3))
    print(model.summary())
    model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=["accuracy"])
    return model
    


In [147]:
model = RNN_model()
model.fit(train_std, tr_eng, batch_size=64, epochs=10, validation_data = (X_test, y_test))

TypeError: ('Keyword argument not understood:', 'init')

In [141]:
def f1(y_true, y_pred):
    def recall(y_true, y_pred):
        """Recall metric.

        Only computes a batch-wise average of recall.

        Computes the recall, a metric for multi-label classification of
        how many relevant items are selected.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        """Precision metric.

        Only computes a batch-wise average of precision.

        Computes the precision, a metric for multi-label classification of
        how many selected items are relevant.
        """
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision
    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [142]:
def Train_Model(model,X_train, y_train, cross_validation = False):

  print('Training and Testing...')
  
  es = EarlyStopping(monitor='val_f1', mode='max', verbose=1, patience=5)
  checkpoint = ModelCheckpoint(model_save_path, monitor='val_f1', verbose=1, save_best_only=True, mode='max')
  callbacks_list = [checkpoint,es]

  if (cross_validation):
    callbacks_list = [es]
  
  his = model.fit(X_train, y_train, validation_split=VALIDATION_SPLIT, epochs=NB_EPOCHS, batch_size=BATCH_SIZE, callbacks=callbacks_list, verbose=1)
  return model,his

In [143]:
MAX_FEATURES = 300
VERBOSITY = 1
VALIDATION_SPLIT = 0.1
NB_EPOCHS = 20
FOLDS = 10
EMBEDDING_SIZE = 300

BATCH_SIZE = 32 # 64, 128
NB_FILTERS = 200 #200
FILTER_LENGTH = 4 # test with 2,3,4,5
# HIDDEN_DIMS = NB_FILTERS * 2
HIDDEN_DIMS = 32
MAX_LEN = 210 #test with other values(only this value work for now)
DROPOUT_VALUE_1 = 0.5 #0.8 #0.3
DROPOUT_VALUE_2 = 0.5
L2_REG= 0.01

RNN = LSTM